-- ============================================================================
-- Agents seed for clean project (new UUIDs generated by DB)
-- ============================================================================

INSERT INTO public.agents (
  name,
  title,
  phone,
  email,
  image_url,
  sort_order,
  is_active
)
VALUES
  ('Evan van Romburgh', 'Sales Specialist', '+27745588877', 'evan@ignite-studios.co.za', NULL, 1, true),
  ('Erin Allen', 'Sales Specialist', '+27716741771', 'erin@ignite-studios.co.za', NULL, 2, true);
